language: ruby
rvm:
- 2.3.0
before_script:
before_script:
  - "export DISPLAY=:99.0"
script:
- bundle exec rake assets:precompile
- bundle exec rake db:test:prepare
- bundle exec rspec spec
- bundle exec rake jasmine:ci
cache: bundler